// Localhost Routes
#Home
GET http://localhost:4000/
#Mario Route
GET http://localhost:4000/mario
#Luigi Route
GET http://localhost:4000/luigi
#All Contacts Route
GET http://localhost:4000/contacts
#Mario Contact Info
GET http://localhost:4000/contacts/65a61fc7c9ae3371bad8b039
#Faby Contact Info
GET http://localhost:4000/contacts/65a6202dc9ae3371bad8b03b
#Caden Contact Info
GET http://localhost:4000/contacts/65a6208fc9ae3371bad8b03c


// Render Routes
#Home
GET https://cse341-winter24-1hz0.onrender.com/
#Mario Route
GET https://cse341-winter24-1hz0.onrender.com/mario
#Luigi Route
GET https://cse341-winter24-1hz0.onrender.com/luigi
#All Contacts Route
GET https://cse341-winter24-1hz0.onrender.com/contacts
#Mario Contact Info
GET https://cse341-winter24-1hz0.onrender.com/contacts/65a61fc7c9ae3371bad8b039
#Faby Contact Info
GET https://cse341-winter24-1hz0.onrender.com/contacts/65a6202dc9ae3371bad8b03b
#Caden Contact Info
GET https://cse341-winter24-1hz0.onrender.com/contacts/65a6208fc9ae3371bad8b03c